In [ ]:
import torch
torch.__version__

'2.3.0+cu121'

# **1. Three Types of Data**
**1. Scalar Data**

**2. Vector Data**

**3. Matrix Data**

## **1.1 Scalar Data**

In [ ]:
scalar_data = torch.tensor(5)
print(f"tensor:{scalar_data}, item:{scalar_data.item()}")

tensor:5, item:5


In [ ]:
print(f"Dimension of scalar data is: {scalar_data.ndim}")
print(f"Shape: {scalar_data.shape}")

Dimension of scalar data is: 0
Shape: torch.Size([])


## **1.2 Vector Data**

In [ ]:
vector_data = torch.tensor([1,2])
print(f"tensor:{vector_data}")
print(f"Dimension of vector_data:{vector_data.ndim}")

tensor:tensor([1, 2])
Dimension of vector_data:1


##**1.3 Matrix Data**

In [ ]:
matrix = torch.tensor([[1,2,3],[4,5,6]])
print(f"Tensor:{matrix}")
print(f"Dimension of Matrix:{matrix.ndim}")
print(f"Shape:{matrix.shape}")

Tensor:tensor([[1, 2, 3],
        [4, 5, 6]])
Dimension of Matrix:2
Shape:torch.Size([2, 3])


In [ ]:
x = torch.tensor(5.1)
x.dtype, x.device

(torch.float32, device(type='cpu'))

# **2. Creation of Tensor**

## **2.1 Random & Range Tensor**

### **`torch.rand()`**

In [ ]:
x = torch.rand(5)
x

tensor([0.8157, 0.9287, 0.5438, 0.0244, 0.4142])

###**`torch.randn()`**

In [ ]:
x = torch.randn(5)
x

tensor([ 1.6947, -0.7933, -0.1532, -0.6467, -1.0131])

###**`torch.range()`**
`torch.range()` will be depricated so better to use `torch.arange()`.

In [ ]:
x = torch.range(1,5,1)
x

<ipython-input-9-98f55cd48a0c>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  x = torch.range(1,5,1)


tensor([1., 2., 3., 4., 5.])

###**`torch.arange()`**
torchh.arange(start, end, step)

In [ ]:
x = torch.arange(0,6,1)
x

tensor([0, 1, 2, 3, 4, 5])

## **2.2 Zeros and Ones**

###**`torch.zeros()`**

In [ ]:
zeros_tensor = torch.zeros(5)
zeros_tensor

tensor([0., 0., 0., 0., 0.])

###**`torch.ones()`**

In [ ]:
ones_tensor = torch.ones(5)
ones_tensor

tensor([1., 1., 1., 1., 1.])

# **3. Seed (Reproducibility)**

In [ ]:
torch.manual_seed(42)
x = torch.randn(1)
x

tensor([0.3367])

# **4. Datatype, Device**

In [ ]:
x = torch.tensor(1.0)
print(f"Datatype:{x.dtype}, device={x.device}")

Datatype:torch.float32, device=cpu


In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

## **`torch.tensor.to()`**

In [ ]:
y = x.to(dtype=torch.int32)
y.dtype

torch.int32

In [ ]:
z = x.type(torch.int32)
z.dtype

torch.int32

# **5. Basic Operations**

##**5.1 Addition**

In [ ]:
torch.manual_seed(42)
x = torch.rand(5)
x,x + 5

(tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904]),
 tensor([5.8823, 5.9150, 5.3829, 5.9593, 5.3904]))

`torch.add()`

In [ ]:
torch.manual_seed(42)
x=torch.rand(5)
torch.add(x,5)

tensor([5.8823, 5.9150, 5.3829, 5.9593, 5.3904])

In [ ]:
## **5.2 Subtraction**

In [ ]:
torch.manual_seed(42)
x = torch.rand(5)
5-x

tensor([4.1177, 4.0850, 4.6171, 4.0407, 4.6096])

`torch.sub()`

In [ ]:
torch.manual_seed(42)
x = torch.rand(5)
torch.sub(5,x)

tensor([4.1177, 4.0850, 4.6171, 4.0407, 4.6096])

##**5.3 Multiplicaiton**

In [ ]:
torch.manual_seed(42)
x = torch.rand(5)
x * 5

tensor([4.4113, 4.5750, 1.9143, 4.7965, 1.9522])

`torch.mul()`

In [ ]:
torch.manual_seed(42)
x = torch.rand(5)
torch.mul(x,5)

tensor([4.4113, 4.5750, 1.9143, 4.7965, 1.9522])

##**5.4 Division**

In [ ]:
torch.manual_seed(42)
x = torch.rand(5)
5/x

tensor([ 5.6672,  5.4645, 13.0595,  5.2121, 12.8058])

`torch.div()`

In [ ]:
torch.manual_seed(42)
x = torch.rand(5)
torch.div(5,x)

tensor([ 5.6672,  5.4645, 13.0595,  5.2121, 12.8058])

##**5.5 Matrix Multiplicaiton**
For matrix multiplication, the shape of two matrix must be compatible i.e. for matrix A & B the outer shape of A must be equal to inner shape of matrix B

In [ ]:
torch.manual_seed(42)
A = torch.rand(size=(2,3))
A, A.shape

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]]),
 torch.Size([2, 3]))

In [ ]:
torch.manual_seed(42)
B = torch.rand(3,4)
B, B.shape

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 torch.Size([3, 4]))

In [ ]:
import time

In [ ]:
%%time
C = A @ B
C

CPU times: user 1.13 ms, sys: 7 µs, total: 1.14 ms
Wall time: 793 µs


tensor([[1.4958, 1.4081, 0.9304, 1.7998],
        [1.5641, 1.1924, 1.0291, 1.5868]])

`torch.matmul()`

In [ ]:
%%time
C = torch.matmul(A,B)
C

CPU times: user 164 µs, sys: 8 µs, total: 172 µs
Wall time: 179 µs


tensor([[1.4958, 1.4081, 0.9304, 1.7998],
        [1.5641, 1.1924, 1.0291, 1.5868]])

# **6. Statistical Operations**

## **6.1 MIN/MAX/MEAN/SUM**

In [ ]:
x = torch.arange(10,150,10)
x

tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130, 140])

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"MEAN: {x.type(torch.float).mean()}")
print(f"sum:{x.sum()}")

Minimum: 10
Maximum: 140
MEAN: 75.0
sum:1050


##**6.2 Positional MIN/MAX**

In [ ]:
print(f"position/index of manimum data:{x.argmin()}")
print(f"position/index of maximum data:{x.argmax()}")

position/index of manimum data:0
position/index of maximum data:13


# **7. Different Useful Operations**

## **7.1 `torch.reshape()`**

In [ ]:
x = torch.arange(1,10,1)
x, x.shape, x.reshape(1,1,1,1,1,1,3,3)

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 torch.Size([9]),
 tensor([[[[[[[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]]]]]]]]))

##**7.2 `torch.squeeze()`**

In [ ]:
y = x.reshape(1,3,3)
z = y.squeeze(dim=0)
y.shape, z.shape, z

(torch.Size([1, 3, 3]),
 torch.Size([3, 3]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

## **7.3 `torch.unsqueeze()`**

In [ ]:
a = z.unsqueeze(dim=0)
a, a.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

## **`torch.permute()`**

In [ ]:
x = torch.rand(1,2,3)
x, x.shape

(tensor([[[0.5779, 0.9040, 0.5547],
          [0.3423, 0.6343, 0.3644]]]),
 torch.Size([1, 2, 3]))

In [ ]:
y = x.permute(1,2,0)
x.shape, y.shape, y

(torch.Size([1, 2, 3]),
 torch.Size([2, 3, 1]),
 tensor([[[0.5779],
          [0.9040],
          [0.5547]],
 
         [[0.3423],
          [0.6343],
          [0.3644]]]))

# **8. PyTorch and Numpy**

In [ ]:
import numpy as np

a = np.arange(1,5,1)
a

array([1, 2, 3, 4])

##`torch.from_numpy()`

In [ ]:
z = torch.from_numpy(a)
z

tensor([1, 2, 3, 4])